# ***NumPy for Machine Learning***

## Objective
Understand NumPy arrays and operations that are essential for data handling in Machine Learning.


### **1. Import NumPy**

In [1]:
import numpy as np

### **2. Create Arrays**

In [2]:
arr = np.array([1, 2, 3, 4, 5])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

arr, matrix

(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3],
        [4, 5, 6]]))

### **3. Shape, Type, Dimension**

In [3]:
arr.shape, matrix.shape, matrix.ndim, matrix.dtype


((5,), (2, 3), 2, dtype('int64'))

### **4. Indexing & Slicing**

In [4]:
arr[1:4]
matrix[:, 1]


array([2, 5])

### **5. Mathematical Operations**

In [5]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

a + b, a * b, np.mean(a), np.std(a)


(array([11, 22, 33]),
 array([10, 40, 90]),
 np.float64(20.0),
 np.float64(8.16496580927726))

### **6. Reshaping**

In [6]:
arr.reshape(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

### **7. Random Numbers (ML Use Case)**

In [7]:
np.random.seed(42)
np.random.rand(3, 3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

### **8. Key Learnings (Markdown)**

## Key Learnings
- NumPy arrays vs Python lists
- Shape, dimension, and reshaping
- Vectorized operations
- Random number generation for ML experiments